In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
import tensorflow as tf
import tensorflow.keras as kr
from tqdm.notebook import tqdm
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
import json

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
song_meta = pd.read_json('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/멜론데이터/song_meta.json', typ = 'frame')
train = pd.read_json('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/멜론데이터/train.json', typ = 'frame')
val = pd.read_json('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/멜론데이터/val.json', typ = 'frame')

In [ ]:
train.head()

                                                tags  ...                updt_date
0                                                [락]  ...  2013-12-19 18:36:19.000
1                                           [추억, 회상]  ...  2014-12-02 16:19:42.000
2                                          [까페, 잔잔한]  ...  2017-08-28 07:09:34.000
3  [연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...  ...  2019-12-05 15:15:18.000
4                                               [댄스]  ...  2011-10-25 13:54:56.000

[5 rows x 6 columns]

In [ ]:
train_data = train[['id', 'songs','like_cnt']]
train_data_unnest = np.dstack((np.repeat(train_data.id.values, list(map(len, train_data.songs))),
                               np.concatenate(train_data.songs.values),
                               np.repeat(train_data.like_cnt.values, list(map(len, train_data.songs)))))
train_data = pd.DataFrame(data = train_data_unnest[0], columns = train_data.columns)
train_data['id'] = train_data['id'].astype(int)
train_data['songs'] = train_data['songs'].astype(int)
train_data['like_cnt'] = train_data['like_cnt'].astype(int)
train_data.columns = ['listid','songid', 'likecnt']

del train_data_unnest
train_data

         listid  songid  likecnt
0         61281  525514       71
1         61281  129701       71
2         61281  383374       71
3         61281  562083       71
4         61281  297861       71
...         ...     ...      ...
5285866  100389  111365       17
5285867  100389   51373       17
5285868  100389  640239       17
5285869  100389   13759       17
5285870  100389  154078       17

[5285871 rows x 3 columns]

In [ ]:
val_data = val[['id', 'songs', 'like_cnt']]
val_data_unnest = np.dstack((np.repeat(val_data.id.values, list(map(len, val_data.songs))),
                             np.concatenate(val_data.songs.values),
                             np.repeat(val_data.like_cnt.values, list(map(len, val_data.songs)))))
val_data = pd.DataFrame(data = val_data_unnest[0], columns = val_data.columns)
val_data['id'] = val_data['id'].astype(int)
val_data['songs'] = val_data['songs'].astype(int)
val_data['like_cnt'] = val_data['like_cnt'].astype(int)
val_data.columns = ['listid','songid', 'likecnt']

del val_data_unnest
val_data

        listid  songid  likecnt
0       118598  373313     1675
1       118598  151080     1675
2       118598  275346     1675
3       118598  696876     1675
4       118598  165237     1675
...        ...     ...      ...
421194   65189  193899       19
421195   65189  398886       19
421196   65189  234875       19
421197   65189  243850       19
421198   65189   83875       19

[421199 rows x 3 columns]

In [ ]:
playlist_map = pd.concat([train_data, val_data], ignore_index=True)
playlist_map

         listid  songid  likecnt
0         61281  525514       71
1         61281  129701       71
2         61281  383374       71
3         61281  562083       71
4         61281  297861       71
...         ...     ...      ...
5707065   65189  193899       19
5707066   65189  398886       19
5707067   65189  234875       19
5707068   65189  243850       19
5707069   65189   83875       19

[5707070 rows x 3 columns]

In [ ]:
like_count = playlist_map.groupby('songid').sum()['likecnt']
(like_count.sort_values(ascending = False) > 60000).sum()

1859

In [ ]:
like_count_60000 = pd.DataFrame(like_count)
like_count_60000.columns = ['likecount']
like_count_60000 = like_count_60000[like_count_60000['likecount'] >= 60000].sort_values(ascending = False, by = 'likecount')
like_count_60000.reset_index(inplace = True)
like_count_60000['songnewid'] = range(len(like_count_60000))
like_count_60000

      songid  likecount  songnewid
0     366786     352819          0
1     133143     277721          1
2     625875     277206          2
3     610933     277176          3
4     580074     272594          4
...      ...        ...        ...
1854   43689      60142       1854
1855  409828      60123       1855
1856  418694      60103       1856
1857  349306      60052       1857
1858  156278      60046       1858

[1859 rows x 3 columns]

In [ ]:
song_meta_60000 = song_meta[song_meta['id'].isin(like_count_60000['songid'])]
song_meta_60000.rename(columns={'id': 'songid'}, inplace=True)
song_meta_60000 = pd.merge(song_meta_60000, like_count_60000, on = 'songid', how = 'left')
song_meta_60000

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                song_gn_dtl_gnr_basket  issue_date  ... likecount  songnewid
0                     [GN1304, GN1301]    20110810  ...     66252       1502
1                     [GN0105, GN0101]    20130404  ...    130794        246
2             [GN0401, GN0403, GN0402]    20151012  ...     81350        951
3                     [GN1301, GN1302]    20070927  ...     79724        994
4     [GN2207, GN1501, GN1506, GN1509]    20010718  ...     69128       1368
...                                ...         ...  ...       ...        ...
1854          [GN1701, GN1703, GN1702]    20020301  ...    200293         33
1855                  [GN0105, GN0101]    20110311  ...     85700        852
1856                          [GN0901]    20150904  ...    106095        501
1857                  [GN0104, GN0101]    20080819  ...     86021        845
1858  [GN0105, GN1501, GN0101, GN1504]    20160510  ...     77713       1057

[1859 rows x 11 columns]

In [ ]:
playlist_map_60000 = playlist_map[playlist_map['songid'].isin(like_count_60000['songid'])]
playlist_map_60000

         listid  songid  likecnt
21        10532  497066        1
28        10532  532114        1
29        10532  586541        1
43        10532    6546        1
44        10532  152422        1
...         ...     ...      ...
5707056   65189  362966       19
5707057   65189  144663       19
5707062   65189  581789       19
5707064   65189  701557       19
5707068   65189  243850       19

[903103 rows x 3 columns]

In [ ]:
playlist_map_60000_newid = pd.merge(playlist_map_60000, like_count_60000, on = 'songid', how = 'left')
del playlist_map_60000_newid['songid']
del playlist_map_60000_newid['likecnt']
playlist_map_60000_newid

        listid  likecount  songnewid
0        10532     207995         26
1        10532     152699        125
2        10532      72717       1233
3        10532     130333        251
4        10532     103515        537
...        ...        ...        ...
903098   65189      64524       1603
903099   65189     173208         69
903100   65189      68308       1399
903101   65189     130391        250
903102   65189     163779         88

[903103 rows x 3 columns]

In [ ]:
num_song = playlist_map_60000_newid.songnewid.nunique()
print(num_song)

1859

In [ ]:
playlist_map_60000_newid_train = playlist_map_60000_newid[
    playlist_map_60000_newid['listid'].isin(train['id'])]
playlist_map_60000_newid_val = playlist_map_60000_newid[playlist_map_60000_newid['listid'].isin(val['id'])]

In [ ]:
num_user_train = playlist_map_60000_newid_train.listid.nunique()
num_user_val = playlist_map_60000_newid_val.listid.nunique()
print(num_user_train)
print(num_user_val)

84596
12053

In [ ]:
playlist_map_60000_newid_trainlog = playlist_map_60000_newid_train
playlist_map_60000_newid_trainlog['likecount'] = np.log(playlist_map_60000_newid_train['likecount'])
playlist_map_60000_newid_vallog = playlist_map_60000_newid_val
playlist_map_60000_newid_vallog['likecount'] = np.log(playlist_map_60000_newid_val['likecount'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
playlist_map_60000_newid_trainlog.to_csv('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/playlist_map_60000_newid_trainlog.csv')
playlist_map_60000_newid_vallog.to_csv('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/playlist_map_60000_newid_vallog.csv')

In [ ]:
playlist_map_60000_newid_trainlog = pd.read_csv('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/playlist_map_60000_newid_trainlog.csv')
playlist_map_60000_newid_vallog = pd.read_csv('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/playlist_map_60000_newid_vallog.csv')

In [ ]:
song_meta_60000.to_csv('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/song_meta_60000.csv')

In [ ]:
user_dict_train = {}
song_dict_train = {}
n_mapped_user_train = 0
n_mapped_song_train = 0
R_train = np.zeros((num_user_train, num_song))
for index, row in tqdm(playlist_map_60000_newid_trainlog.iterrows()):
  if row.listid in user_dict_train:
    user_cur = user_dict_train[row.listid]
  else:
    user_cur = n_mapped_user_train
    n_mapped_user_train += 1
    user_dict_train[row.listid] = user_cur
  if row.songnewid in song_dict_train:
    song_cur = song_dict_train[row.songnewid]
  else:
    song_cur = n_mapped_song_train
    n_mapped_song_train += 1
    song_dict_train[row.songnewid] = song_cur
  R_train[user_cur, song_cur] = row.likecount

0it [00:00, ?it/s]

In [ ]:
user_dict_val = {}
song_dict_val = {}
n_mapped_user_val = 0
n_mapped_song_val = 0
R_val = np.zeros((num_user_val, num_song))
for index, row in tqdm(playlist_map_60000_newid_vallog.iterrows()):
  if row.listid in user_dict_val:
    user_cur = user_dict_val[row.listid]
  else:
    user_cur = n_mapped_user_val
    n_mapped_user_val += 1
    user_dict_val[row.listid] = user_cur
  if row.songnewid in song_dict_val:
    song_cur = song_dict_val[row.songnewid]
  else:
    song_cur = n_mapped_song_val
    n_mapped_song_val += 1
    song_dict_val[row.songnewid] = song_cur
  R_val[user_cur, song_cur] = row.likecount

0it [00:00, ?it/s]

In [ ]:
R_train_tr, R_train_te = train_test_split(R_train, test_size = 0.1)

In [ ]:
input_ = kr.layers.Input(shape=R_train.shape[1:])
hidden1 = kr.layers.Dense(600, activation='relu', kernel_regularizer=kr.regularizers.l2(0.001))(input_)
hidden2 = kr.layers.Dense(128, activation='relu', kernel_regularizer=kr.regularizers.l2(0.001))(hidden1)
hidden3 = kr.layers.Dense(600, activation='relu', kernel_regularizer=kr.regularizers.l2(0.001))(hidden2)
output_ = kr.layers.Dense(R_train.shape[1], kernel_regularizer=kr.regularizers.l2(0.01))(hidden3)
model = kr.Model(inputs=[input_], outputs=[output_])

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(R_train_tr, R_train_tr, validation_data=(R_train_te, R_train_te), epochs=10)

Epoch 1/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1188.7885 - accuracy: 0.0155 - val_loss: 1289.1746 - val_accuracy: 0.0178
Epoch 2/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1158.6384 - accuracy: 0.0172 - val_loss: 1170.8872 - val_accuracy: 0.0178
Epoch 3/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1151.7272 - accuracy: 0.0172 - val_loss: 1018.5156 - val_accuracy: 0.0178
Epoch 4/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1130.4246 - accuracy: 0.0172 - val_loss: 1145.6025 - val_accuracy: 0.0178
Epoch 5/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1168.0638 - accuracy: 0.0178 - val_loss: 1278.3892 - val_accuracy: 0.0184
Epoch 6/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1177.8348 - accuracy: 0.0183 - val_loss: 1231.3533 - val_accuracy: 0.0189
Epoch 7/10
2380/2380 [==============================] - 27s 11ms/step - loss: 1146.0544 - accuracy: 0.0184 - val_loss: 993.8458 - val_accuracy: 0.0203
Epoch 8/10
2380/2380 [==============================] - 28s 12ms/step - loss: 1129.4590 - accuracy: 0.0182 - val_loss: 1202.9185 - val_accuracy: 0.0189
Epoch 9/10
2380/2380 [==============================] - 29s 12ms/step - loss: 1113.2411 - accuracy: 0.0188 - val_loss: 983.1295 - val_accuracy: 0.0182
Epoch 10/10
2380/2380 [==============================] - 28s 12ms/step - loss: 1109.2815 - accuracy: 0.0183 - val_loss: 1201.9397 - val_accuracy: 0.0196

In [ ]:
model.save('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/simple_40000b.h5')

In [ ]:
model = load_model('/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/오토인코더_w2v_앙상블/simple_40000b.h5')

In [ ]:
a = pd.DataFrame(data=model.predict(R_val))
a

               0             1     ...         1857         1858
0         24.253807    -51.254528  ...     6.378341   -47.855728
1      -1470.929565  -1355.127563  ...   233.100632   162.703857
2         38.976582    -77.060745  ...    13.540292   -68.183197
3      -2371.488281  -2173.900146  ...   363.191650   255.296524
4       -705.918884   -645.627441  ...   103.629875    72.203575
...             ...           ...  ...          ...          ...
12048 -14232.462891 -13067.175781  ...  2229.468018  1573.764648
12049  -3509.583984  -3227.135742  ...   553.069214   388.923370
12050  -5620.127441  -5158.524902  ...   878.690247   619.994934
12051  -7789.976074  -7154.006348  ...  1223.043213   863.405090
12052  -6223.384277  -5714.099121  ...   975.778320   688.970459

[12053 rows x 1859 columns]

In [ ]:
b = song_meta_60000.sort_values('songnewid')
b.reset_index(inplace = True)
b

      index                    song_gn_dtl_gnr_basket  ...  likecount songnewid
0       932  [GN0805, GN0509, GN0502, GN0801, GN0501]  ...     352819         0
1       367  [GN0805, GN0501, GN0502, GN0801, GN0509]  ...     277721         1
2      1658                                  [GN0901]  ...     277206         2
3      1613  [GN0805, GN0501, GN0502, GN0801, GN0509]  ...     277176         3
4      1541                          [GN0101, GN0103]  ...     272594         4
...     ...                                       ...  ...        ...       ...
1854    118                          [GN0105, GN0101]  ...      60142      1854
1855   1065          [GN0501, GN0101, GN0506, GN0509]  ...      60123      1855
1856   1095                                  [GN0901]  ...      60103      1856
1857    892                                  [GN1201]  ...      60052      1857
1858    417                          [GN0303, GN0301]  ...      60046      1858

[1859 rows x 12 columns]

In [ ]:
c = b['songid']
a.columns = c.tolist()
a

             366786        133143  ...       349306       156278
0         24.253807    -51.254528  ...     6.378341   -47.855728
1      -1470.929565  -1355.127563  ...   233.100632   162.703857
2         38.976582    -77.060745  ...    13.540292   -68.183197
3      -2371.488281  -2173.900146  ...   363.191650   255.296524
4       -705.918884   -645.627441  ...   103.629875    72.203575
...             ...           ...  ...          ...          ...
12048 -14232.462891 -13067.175781  ...  2229.468018  1573.764648
12049  -3509.583984  -3227.135742  ...   553.069214   388.923370
12050  -5620.127441  -5158.524902  ...   878.690247   619.994934
12051  -7789.976074  -7154.006348  ...  1223.043213   863.405090
12052  -6223.384277  -5714.099121  ...   975.778320   688.970459

[12053 rows x 1859 columns]

In [ ]:
d = playlist_map_60000_newid_vallog['listid'].unique()
d

array([118598,  45144, 127575, ..., 122127,  77438,  65189])

In [ ]:
e = []
for i in tqdm(range(len(a))):
    f = ((a.iloc[i, :].sort_values(ascending = False)).index)[:100]
    f = f.tolist()
    e.append(f)

  0%|          | 0/12053 [00:00<?, ?it/s]

In [ ]:
g = pd.DataFrame({'id' : d, 'songs' : e})
g

           id                                              songs
0      118598  [594116, 427246, 22573, 311, 518960, 207558, 2...
1       45144  [686809, 407044, 205247, 144632, 413952, 41318...
2      127575  [594116, 427246, 22573, 311, 207558, 518960, 2...
3       53131  [686809, 407044, 205247, 144632, 413952, 41318...
4       44037  [686809, 407044, 205247, 144632, 413952, 41318...
...       ...                                                ...
12048   17766  [686809, 407044, 205247, 144632, 413952, 41318...
12049  101722  [686809, 407044, 205247, 144632, 413952, 41318...
12050  122127  [686809, 407044, 205247, 144632, 413952, 41318...
12051   77438  [686809, 407044, 205247, 144632, 413952, 41318...
12052   65189  [686809, 407044, 205247, 144632, 413952, 41318...

[12053 rows x 2 columns]

-----------------------------------------------------

In [ ]:
result = pd.read_json("/content/drive/MyDrive/KUBIG 2021-2/추천시스템 프로젝트/리더보드 제출 모델 및 결과파일/word2vec_Khaii/results.json")
result

           id  ...                                               tags
0      118598  ...  [OST, 디즈니, 애니메이션, 영화, 기분전환, 추억, 디즈니OST, 영화음악, ...
1      131447  ...      [기분전환, 감성, 휴식, 발라드, 잔잔한, 드라이브, 힐링, 사랑, 새벽, 밤]
2       51464  ...          [발라드, 슬픔, 이별, 추억, 회상, 새벽, 밤, 잔잔한, 여행, 설렘]
3       45144  ...       [감성, 발라드, 사랑, 이별, 기분전환, 가을, 잔잔한, 새벽, 카페, 휴식]
4       79929  ...     [CCM, 찬양, 은혜, 예배, 교회, 국내ccm, 워십, 찬송, 제이어스, 감사]
...       ...  ...                                                ...
23010  101722  ...         [새벽, 밤, 추억, 이별, 슬픔, 회상, 힐링, 휴식, 발라드, 기분전환]
23011  122127  ...         [추억, 회상, 사랑, 힐링, 휴식, 부모님, 엄마, 잔잔한, 새벽, 설렘]
23012   77438  ...      [팝, 팝송, 기분전환, Pop, 드라이브, 휴식, 힐링, 카페, 잔잔한, 감성]
23013   36231  ...  [클래식, 잔잔한, 피아노, 아기클래식, 힐링, 조성진, 0살, 첼로, 기분전환, 휴식]
23014   65189  ...      [봄, 벚꽃, 봄노래, 사랑, 설렘, 기분전환, 봄날, 봄캐롤, 드라이브, 여행]

[23015 rows x 3 columns]

In [ ]:
final = pd.merge(result, g, on = 'id', how = 'left')
final

           id  ...                                            songs_y
0      118598  ...  [594116, 427246, 22573, 311, 518960, 207558, 2...
1      131447  ...                                                NaN
2       51464  ...                                                NaN
3       45144  ...  [686809, 407044, 205247, 144632, 413952, 41318...
4       79929  ...                                                NaN
...       ...  ...                                                ...
23010  101722  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23011  122127  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23012   77438  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23013   36231  ...                                                NaN
23014   65189  ...  [686809, 407044, 205247, 144632, 413952, 41318...

[23015 rows x 4 columns]

In [ ]:
final['songs'] = np.where(pd.notnull(final['songs_y']) == True, final['songs_y'], final['songs_x'])
final

           id  ...                                              songs
0      118598  ...  [594116, 427246, 22573, 311, 518960, 207558, 2...
1      131447  ...  [144663, 116573, 357367, 366786, 654757, 13314...
2       51464  ...  [291080, 270647, 358818, 659416, 193610, 29532...
3       45144  ...  [686809, 407044, 205247, 144632, 413952, 41318...
4       79929  ...  [412769, 211220, 70314, 242124, 445299, 106129...
...       ...  ...                                                ...
23010  101722  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23011  122127  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23012   77438  ...  [686809, 407044, 205247, 144632, 413952, 41318...
23013   36231  ...  [548041, 50031, 46497, 699175, 229703, 2826, 1...
23014   65189  ...  [686809, 407044, 205247, 144632, 413952, 41318...

[23015 rows x 5 columns]

In [ ]:
real_final = pd.DataFrame(final[['id','songs','tags']])
real_final

           id  ...                                               tags
0      118598  ...  [OST, 디즈니, 애니메이션, 영화, 기분전환, 추억, 디즈니OST, 영화음악, ...
1      131447  ...      [기분전환, 감성, 휴식, 발라드, 잔잔한, 드라이브, 힐링, 사랑, 새벽, 밤]
2       51464  ...          [발라드, 슬픔, 이별, 추억, 회상, 새벽, 밤, 잔잔한, 여행, 설렘]
3       45144  ...       [감성, 발라드, 사랑, 이별, 기분전환, 가을, 잔잔한, 새벽, 카페, 휴식]
4       79929  ...     [CCM, 찬양, 은혜, 예배, 교회, 국내ccm, 워십, 찬송, 제이어스, 감사]
...       ...  ...                                                ...
23010  101722  ...         [새벽, 밤, 추억, 이별, 슬픔, 회상, 힐링, 휴식, 발라드, 기분전환]
23011  122127  ...         [추억, 회상, 사랑, 힐링, 휴식, 부모님, 엄마, 잔잔한, 새벽, 설렘]
23012   77438  ...      [팝, 팝송, 기분전환, Pop, 드라이브, 휴식, 힐링, 카페, 잔잔한, 감성]
23013   36231  ...  [클래식, 잔잔한, 피아노, 아기클래식, 힐링, 조성진, 0살, 첼로, 기분전환, 휴식]
23014   65189  ...      [봄, 벚꽃, 봄노래, 사랑, 설렘, 기분전환, 봄날, 봄캐롤, 드라이브, 여행]

[23015 rows x 3 columns]

In [ ]:
res_lst = []

for i in range(real_final.shape[0]):
  res_lst.append({
                "id": real_final['id'][i],
                "songs": real_final['songs'][i],
                "tags": real_final['tags'][i]
            })

In [ ]:
import io
import os
import json
import distutils.dir_util
from collections import Counter

import numpy as np


def write_json(data, fname):
    def _conv(o):
        if isinstance(o, np.int64) or isinstance(o, np.int32):
            return int(o)
        raise TypeError

    parent = os.path.dirname(fname)
    distutils.dir_util.mkpath("./arena_data/" + parent)
    with io.open("./arena_data/" + fname, "w", encoding="utf8") as f:
        json_str = json.dumps(data, ensure_ascii=False, default=_conv)
        f.write(json_str)

In [ ]:
write_json(res_lst, 'results/results.json')